### ISSUE TITLE
fix: slow growth parameter changes ignores some nb pairs

### ISSUE THREAD

**Issue by ehhartmann** [graeter-group/kimmdy#421]
for a system with atoms 1-2 - - 3-4 where the 2-3 bond just broke, the 2-3 nb interaction is turned on but not 1-3 and 2-4 etc. This causes the charged peptide example to fail and is undesirable in general

**Comment by KRiedmiller** [comment]
Offender: https://github.com/graeter-group/kimmdy/blob/9336a9111cb6167ba2fa6aecd48ce5272c16cb20/src/kimmdy/coordinates.py#L354-L355

**Comment by KRiedmiller** [comment]
Issue: In the transition topology, there is no interaction between 1-3 and 2-4. For bonds, there is a morse potential introduced mimicking LJ, but not for 1-3 or 1-4 interactions.
