### ISSUE TITLE
write topology changes order of atomtype parameters

### ISSUE THREAD

**Issue by ehhartmann** [graeter-group/kimmdy#454]
https://github.com/graeter-group/kimmdy/blob/451f3fd02c2bf942939c2576fd13465916be4463/src/kimmdy/topology/atomic.py#L200

Because of cg systems, atomtype.at_num got optional but optional fields go to the end of the class attributes. When writing the topology, at_num ends up at the end of the line and not at second position as before.

**Comment by ehhartmann** [comment]
Replacing None with empty string would make it work

**Comment by jmbuhr** [comment]
ah, true, we deal with this when parsing
https://github.com/graeter-group/kimmdy/blob/451f3fd02c2bf942939c2576fd13465916be4463/src/kimmdy/topology/atomic.py#L203-L216

but don't differentiate when writing out.
