### ISSUE TITLE
truncate_sim_files for "just reactions on a precomputed trajectory" fails due to working directory issues

### ISSUE THREAD

**Issue by jmbuhr** [graeter-group/kimmdy#459]
and removes the trajectory file

**Comment by jmbuhr** [comment]
wip in https://github.com/graeter-group/kimmdy/pull/458

**Comment by KRiedmiller** [comment]
https://github.com/graeter-group/kimmdy/pull/458#discussion_r1676007065_

**Comment by KRiedmiller** [comment]
One option would be to create links to the potentially big files in the setup task. Then, in truncate_sim_file we can check whether it is a link, and if so, replace the link with a copy. That way, the expensive copying is only performed if necessary.
It requires a modification at every point where we would modify the file, but I think `truncate_sim_files` should be the only one.
